version: '3.8'

services:


  sso-api:
    build:
      context: .
      dockerfile: SSO.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=SSOIdentityDb;User Id=sa;Password=MyPass@123;TrustServerCertificate=True;Encrypt=False;
    ports:
      - "5253:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  promotions-api:
    build:
      context: .
      dockerfile: Promotions.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=PromotionsDb;User Id=sa;Password=MyPass@123;TrustServerCertificate=True;Encrypt=False;
      - ConnectionStrings__SsoConnection=Server=host.docker.internal,1433;Database=SSOIdentityDb;User Id=sa;Password=MyPass@123;TrustServerCertificate=True;Encrypt=False;
    ports:
      - "5137:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api-gateway:
    build:
      context: .
      dockerfile: MyCompany.ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SSO_URL=http://sso-api:8080
      - PROMOTIONS_URL=http://promotions-api:8080
    ports:
      - "5000:8080"
    depends_on:
      - sso-api
      - promotions-api

  webapp:
    build:
      context: MyCompany.WebApp
      dockerfile: Dockerfile
    ports:
      - "5001:80"
      - "5003:5002"
    depends_on:
      - api-gateway
