CREATE TABLE [dbo].[TA501DELIVERYPOINTS] (
    [IDACTION]         INT      NOT NULL,
    [CODDELIVERYPOINT] INT      NOT NULL,
    [FLGINCLUSION]     BIT      NULL,
    [CODHER]           INT      NULL,
    [CODNODE]          INT      NULL,
    [IDLEVEL]          INT      NULL,
    [DTESTART]         DATETIME NULL,
    [CODDIV]           INT      NULL,
    PRIMARY KEY CLUSTERED ([IDACTION] ASC, [CODDELIVERYPOINT] ASC),
    CONSTRAINT [FK_TA501DELIVERYPOINTS_RELATIONS_CUST] FOREIGN KEY ([CODHER], [CODDIV], [CODNODE], [IDLEVEL], [DTESTART]) REFERENCES [dbo].[TB0042RELATIONS_CUST] ([CODHER], [CODDIV], [CODNODE], [IDLEVEL], [DTESTART]),
    CONSTRAINT [FK_TA501DELIVERYPOINTS_TA500PROMOACTION] FOREIGN KEY ([IDACTION]) REFERENCES [dbo].[TA500PROMOACTION] ([IDACTION])
);

