CREATE TABLE [dbo].[TA500PROMOACTION] (
    [IDACTION]        INT            NOT NULL,
    [DESACTION]       NVARCHAR (100) NULL,
    [CODDIV]          INT            NULL,
    [CODCONTRACTOR]   INT            NULL,
    [LEVCONTRACTOR]   INT            NULL,
    [DTESTARTSELLIN]  DATETIME       NULL,
    [DTEENDSELLIN]    DATETIME       NULL,
    [DTESTARTSELLOUT] DATETIME       NULL,
    [DTEENDSELLOUT]   DATETIME       NULL,
    [DOCUMENTKEY]     NVARCHAR (50)  NULL,
    [DTEHOST]         DATETIME       NULL,
    [LEVPARTICIPANTS] INT            NULL,
    PRIMARY KEY CLUSTERED ([IDACTION] ASC)
);

