CREATE TABLE [dbo].[TA5026PRODUCTDETAILS] (
    [IDACTION]     INT           NOT NULL,
    [CODPRODUCT]   BIGINT        NOT NULL,
    [LEVPRODUCT]   INT           NOT NULL,
    [CODDISPLAY]   NVARCHAR (50) NOT NULL,
    [CODDIV]       INT           NOT NULL,
    [CODNODEO]     INT           NOT NULL,
    [FLGINCLUSION] BIT           NULL,
    PRIMARY KEY CLUSTERED ([IDACTION] ASC, [CODPRODUCT] ASC, [LEVPRODUCT] ASC, [CODDISPLAY] ASC, [CODDIV] ASC, [CODNODEO] ASC),
    CONSTRAINT [FK_TA5026PRODUCTDETAILS_TA502PRODUCTS] FOREIGN KEY ([IDACTION], [CODPRODUCT]) REFERENCES [dbo].[TA502PRODUCTS] ([IDACTION], [CODPRODUCT]),
    CONSTRAINT [FK_TA5026PRODUCTDETAILS_TA5150PROMOARTICLES] FOREIGN KEY ([CODDIV], [CODNODEO]) REFERENCES [dbo].[TA5150PROMOARTICLES] ([CODDIV], [CODNODEO])
);

