CREATE TABLE [dbo].[TA502PRODUCTS] (
    [IDACTION]      INT             NOT NULL,
    [CODPRODUCT]    BIGINT          NOT NULL,
    [LEVPRODUCT]    INT             NOT NULL,
    [CODDISPLAY]    NVARCHAR (50)   NOT NULL,
    [CODDIV]        INT             NULL,
    [QTYESTIMATED]  DECIMAL (18, 3) NULL,
    [PERCDISCOUNT1] DECIMAL (5, 2)  NULL,
    [PERCDISCOUNT2] DECIMAL (5, 2)  NULL,
    [NUMMEASUREA]   DECIMAL (18, 3) NULL,
    [CODMEASURE]    NVARCHAR (10)   NULL,
    PRIMARY KEY CLUSTERED ([IDACTION] ASC, [CODPRODUCT] ASC, [LEVPRODUCT] ASC, [CODDISPLAY] ASC),
    CONSTRAINT [FK_TA502PRODUCTS_TA500PROMOACTION] FOREIGN KEY ([IDACTION]) REFERENCES [dbo].[TA500PROMOACTION] ([IDACTION]),
    CONSTRAINT [FK_TA502PRODUCTS_TA5118PROMOMEASUREFIELDS] FOREIGN KEY ([CODDIV], [CODMEASURE]) REFERENCES [dbo].[TA5118PROMOMEASUREFIELDS] ([CODDIV], [CODMEASURE]),
    CONSTRAINT [UQ_TA502PRODUCTS_IDACTION_CODPRODUCT] UNIQUE NONCLUSTERED ([IDACTION] ASC, [CODPRODUCT] ASC)
);

