CREATE TABLE [dbo].[TA5150PROMOARTICLES] (
    [CODDIV]      NVARCHAR (50) NOT NULL,
    [CODNODEO]    NVARCHAR (50) NOT NULL,
    [CODNODE1]    NVARCHAR (50) NULL,
    [CODNODE2]    NVARCHAR (50) NULL,
    [FROMNODEFIN] BIT NULL,
    PRIMARY KEY CLUSTERED ([CODDIV] ASC, [CODNODEO] ASC)
);

