CREATE TABLE [dbo].[TA5118PROMOMEASUREFIELDS] (
    [CODDIV]     NVARCHAR (50)  NOT NULL,
    [CODMEASURE] NVARCHAR (50)  NOT NULL,
    [FIELDNAME]  NVARCHAR (100) NOT NULL,
    [FORMULA]    NVARCHAR (500) NULL,
    PRIMARY KEY CLUSTERED ([CODDIV] ASC, [CODMEASURE] ASC, [FIELDNAME] ASC)
);

