CREATE TABLE [dbo].[TA5150PROMOARTICLES] (
    [CODDIV]      INT NOT NULL,
    [CODNODEO]    INT NOT NULL,
    [CODNODE1]    INT NULL,
    [CODNODE2]    INT NULL,
    [FROMNODEFIN] BIT NULL,
    PRIMARY KEY CLUSTERED ([CODDIV] ASC, [CODNODEO] ASC)
);

