CREATE TABLE [dbo].[TA5118PROMOMEASUREFIELDS] (
    [CODDIV]     INT            NOT NULL,
    [CODMEASURE] NVARCHAR (10)  NOT NULL,
    [FIELDNAME]  NVARCHAR (50)  NOT NULL,
    [FORMULA]    NVARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([CODDIV] ASC, [CODMEASURE] ASC, [FIELDNAME] ASC),
    CONSTRAINT [UQ_TA5118PROMOMEASUREFIELDS_CODDIV_CODMEASURE] UNIQUE NONCLUSTERED ([CODDIV] ASC, [CODMEASURE] ASC)
);

