CREATE TABLE [dbo].[TA8012PARTICIPANTS] (
    [IDACTION]       INT      NOT NULL,
    [CODPARTICIPANT] BIGINT   NOT NULL,
    [FLGINCLUSION]   BIT      NULL,
    [CODHER]         INT      NULL,
    [CODDIV]         INT      NULL,
    [CODNODE]        INT      NULL,
    [IDLEVEL]        INT      NULL,
    [DTESTART]       DATETIME NULL,
    PRIMARY KEY CLUSTERED ([IDACTION] ASC, [CODPARTICIPANT] ASC),
    CONSTRAINT [FK_TA8012PARTICIPANTS_RELATIONS_CUST] FOREIGN KEY ([CODHER], [CODDIV], [CODNODE], [IDLEVEL], [DTESTART]) REFERENCES [dbo].[TB0042RELATIONS_CUST] ([CODHER], [CODDIV], [CODNODE], [IDLEVEL], [DTESTART]),
    CONSTRAINT [FK_TA8012PARTICIPANTS_TA500PROMOACTION] FOREIGN KEY ([IDACTION]) REFERENCES [dbo].[TA500PROMOACTION] ([IDACTION])
);

