CREATE TABLE [dbo].[TB0042RELATIONS_CUST] (
    [CODHER]         INT      NOT NULL,
    [CODDIV]         INT      NOT NULL,
    [CODNODE]        INT      NOT NULL,
    [IDLEVEL]        INT      NOT NULL,
    [DTESTART]       DATETIME NOT NULL,
    [COOPAREANTNODE] INT      NULL,
    [DTEEND]         DATETIME NULL,
    PRIMARY KEY CLUSTERED ([CODHER] ASC, [CODDIV] ASC, [CODNODE] ASC, [IDLEVEL] ASC, [DTESTART] ASC)
);

