CREATE TABLE [dbo].[TB0042RELATIONS_CUST] (
    [CODHER]         NVARCHAR (50) NOT NULL,
    [CODDIV]         NVARCHAR (50) NOT NULL,
    [CODNODE]        NVARCHAR (50) NOT NULL,
    [IDLEVEL]        INT           NOT NULL,
    [DTESTART]       DATETIME      NOT NULL,
    [COOPAREANTNODE] NVARCHAR (50) NULL,
    [DTEEND]         DATETIME NULL,
    PRIMARY KEY CLUSTERED ([CODHER] ASC, [CODDIV] ASC, [CODNODE] ASC, [IDLEVEL] ASC, [DTESTART] ASC)
);

