// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Promotions.Infrastructure.Persistence;

#nullable disable

namespace Promotions.Infrastructure.Migrations
{
    [DbContext(typeof(PromotionsDbContext))]
    [Migration("20251230132713_AddDeliveryPointsTable")]
    partial class AddDeliveryPointsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Promotions.Domain.DeliveryPoints.PromoDeliveryPoint", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int")
                        .HasColumnName("ID_ACTION");

                    b.Property<string>("CodDeliveryPoint")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODDELIVERYPOINT");

                    b.Property<bool>("FlgInclusion")
                        .HasColumnType("bit")
                        .HasColumnName("FLGINCLUSION");

                    b.HasKey("IdAction", "CodDeliveryPoint");

                    b.HasIndex("IdAction")
                        .HasDatabaseName("IX_TA5014DELIVERYPOINTS_ID_ACTION");

                    b.ToTable("TA5014DELIVERYPOINTS", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.Measures.PromoMeasureField", b =>
                {
                    b.Property<string>("CodDiv")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CODDIV");

                    b.Property<string>("CodMeasure")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CODMEASURE");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FIELDNAME");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FORMULA");

                    b.HasKey("CodDiv", "CodMeasure", "FieldName");

                    b.ToTable("TA5118PROMOMEASUREFIELDS", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.Participants.PromoParticipants", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int")
                        .HasColumnName("ID_ACTION");

                    b.Property<string>("CodParticipant")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CODPARTICIPANT");

                    b.Property<bool>("FlgInclusion")
                        .HasColumnType("bit")
                        .HasColumnName("FLGINCLUSION");

                    b.HasKey("IdAction", "CodParticipant");

                    b.ToTable("TA5012PARTICIPANTS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
