// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Promotions.Infrastructure.Persistence;

#nullable disable

namespace Promotions.Infrastructure.Migrations
{
    [DbContext(typeof(PromotionsDbContext))]
    [Migration("20251218083313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Promotions.Domain.Measures.PromoMeasureField", b =>
                {
                    b.Property<string>("CodDiv")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CODDIV");

                    b.Property<string>("CodMeasure")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CODMEASURE");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("FIELDNAME");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FORMULA");

                    b.HasKey("CodDiv", "CodMeasure", "FieldName");

                    b.ToTable("TA5118PROMOMEASUREFIELDS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
