// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Promotions.Infrastructure.Persistence;

#nullable disable

namespace Promotions.Infrastructure.Migrations
{
    [DbContext(typeof(PromotionsDbContext))]
    [Migration("20260107061515_RemovePromoActionCustomerFKs")]
    partial class RemovePromoActionCustomerFKs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Promotions.Domain.Articles.PromoArticle", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<string>("CodProduct")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LevProduct")
                        .HasColumnType("int");

                    b.Property<string>("CodDisplay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodDiv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODDIV");

                    b.Property<string>("CodNode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODNODE");

                    b.Property<string>("CodNode1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODNODE1");

                    b.Property<string>("CodNode2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODNODE2");

                    b.Property<string>("CodNodeN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODNODE_N");

                    b.HasKey("IdAction", "CodProduct", "LevProduct", "CodDisplay", "CodDiv", "CodNode");

                    b.HasIndex("IdAction", "CodProduct", "LevProduct", "CodDisplay", "CodNode", "CodDiv");

                    b.ToTable("TA5150PROMOARTICLE", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.CustomerRelations.CustomerRelation", b =>
                {
                    b.Property<string>("CodHier")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodDiv")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodNode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("IdLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("DteStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodParentNode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("DteEnd")
                        .HasColumnType("datetime2");

                    b.HasKey("CodHier", "CodDiv", "CodNode", "IdLevel", "DteStart");

                    b.ToTable("TB0042RELATIONS_CUST", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.DeliveryPoints.PromoDeliveryPoint", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int")
                        .HasColumnName("ID_ACTION");

                    b.Property<string>("CodDeliveryPoint")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODDELIVERYPOINT");

                    b.Property<string>("CodDiv")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodHier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodNode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("DteStart")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FlgInclusion")
                        .HasColumnType("bit")
                        .HasColumnName("FLGINCLUSION");

                    b.Property<int>("IdLevel")
                        .HasColumnType("int");

                    b.HasKey("IdAction", "CodDeliveryPoint");

                    b.HasIndex("IdAction")
                        .HasDatabaseName("IX_TA5014DELIVERYPOINTS_ID_ACTION");

                    b.HasIndex("CodHier", "CodDiv", "CodNode", "IdLevel", "DteStart");

                    b.ToTable("TA5014DELIVERYPOINTS", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.Measures.PromoMeasureField", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<string>("CodProduct")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LevProduct")
                        .HasColumnType("int");

                    b.Property<string>("CodDisplay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodDiv")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CODDIV");

                    b.Property<string>("CodMeasure")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODMEASURE");

                    b.Property<string>("FieldName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FIELDNAME");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FORMULA");

                    b.HasKey("IdAction", "CodProduct", "LevProduct", "CodDisplay", "CodDiv", "CodMeasure", "FieldName");

                    b.ToTable("TA5118PROMOMEASUREFIELDS", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.Participants.PromoParticipants", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int")
                        .HasColumnName("ID_ACTION");

                    b.Property<string>("CodParticipant")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CODPARTICIPANT");

                    b.Property<string>("CodDiv")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodHier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodNode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("DteStart")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FlgInclusion")
                        .HasColumnType("bit")
                        .HasColumnName("FLGINCLUSION");

                    b.Property<int>("IdLevel")
                        .HasColumnType("int");

                    b.HasKey("IdAction", "CodParticipant");

                    b.HasIndex("CodHier", "CodDiv", "CodNode", "IdLevel", "DteStart");

                    b.ToTable("TA5012PARTICIPANTS", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.ProductDetails.PromoProductDetail", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<string>("CodProduct")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LevProduct")
                        .HasColumnType("int");

                    b.Property<string>("CodDisplay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodNode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodDiv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("FlgInclusion")
                        .HasColumnType("bit");

                    b.HasKey("IdAction", "CodProduct", "LevProduct", "CodDisplay", "CodNode", "CodDiv");

                    b.ToTable("TA5026PRODUCTDETAILS", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.Products.PromoProduct", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<string>("CodProduct")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LevProduct")
                        .HasColumnType("int");

                    b.Property<string>("CodDisplay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodDiv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodMeasure")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("NumMeasure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PerceDiscount1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PerceDiscount2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QtyEstimated")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdAction", "CodProduct", "LevProduct", "CodDisplay");

                    b.ToTable("TA5020PRODUCTS", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.PromoActions.PromoAction", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int")
                        .HasColumnName("ID_ACTION");

                    b.Property<string>("CodContractor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CODCONTRACTOR");

                    b.Property<string>("CodDiv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CODDIV");

                    b.Property<string>("DocumentKey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOCUMENTKEY");

                    b.Property<DateTime>("DteEndSellIn")
                        .HasColumnType("datetime2")
                        .HasColumnName("DTEENDSELLIN");

                    b.Property<DateTime>("DteEndSellOut")
                        .HasColumnType("datetime2")
                        .HasColumnName("DTEENDSELLOUT");

                    b.Property<DateTime>("DteStartSellIn")
                        .HasColumnType("datetime2")
                        .HasColumnName("DTESTARTSELLIN");

                    b.Property<DateTime>("DteStartSellOut")
                        .HasColumnType("datetime2")
                        .HasColumnName("DTESTARTSELLOUT");

                    b.Property<DateTime?>("DteToShost")
                        .HasColumnType("datetime2")
                        .HasColumnName("DTETOSHOST");

                    b.Property<int?>("LevParticipants")
                        .HasColumnType("int")
                        .HasColumnName("LEVPARTICIPANTS");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESACTION");

                    b.HasKey("IdAction");

                    b.ToTable("TA500PROMOACTION", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.Articles.PromoArticle", b =>
                {
                    b.HasOne("Promotions.Domain.ProductDetails.PromoProductDetail", "ProductDetail")
                        .WithMany("Articles")
                        .HasForeignKey("IdAction", "CodProduct", "LevProduct", "CodDisplay", "CodNode", "CodDiv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("Promotions.Domain.DeliveryPoints.PromoDeliveryPoint", b =>
                {
                    b.HasOne("Promotions.Domain.PromoActions.PromoAction", "Action")
                        .WithMany("DeliveryPoints")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Promotions.Domain.CustomerRelations.CustomerRelation", "Relation")
                        .WithMany("DeliveryPoints")
                        .HasForeignKey("CodHier", "CodDiv", "CodNode", "IdLevel", "DteStart")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("Promotions.Domain.Measures.PromoMeasureField", b =>
                {
                    b.HasOne("Promotions.Domain.Products.PromoProduct", "Product")
                        .WithMany("MeasureFields")
                        .HasForeignKey("IdAction", "CodProduct", "LevProduct", "CodDisplay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Promotions.Domain.Participants.PromoParticipants", b =>
                {
                    b.HasOne("Promotions.Domain.PromoActions.PromoAction", "Action")
                        .WithMany("Participants")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Promotions.Domain.CustomerRelations.CustomerRelation", "Relation")
                        .WithMany("Participants")
                        .HasForeignKey("CodHier", "CodDiv", "CodNode", "IdLevel", "DteStart")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("Promotions.Domain.ProductDetails.PromoProductDetail", b =>
                {
                    b.HasOne("Promotions.Domain.Products.PromoProduct", "Product")
                        .WithMany("Details")
                        .HasForeignKey("IdAction", "CodProduct", "LevProduct", "CodDisplay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Promotions.Domain.Products.PromoProduct", b =>
                {
                    b.HasOne("Promotions.Domain.PromoActions.PromoAction", "Action")
                        .WithMany("Products")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");
                });

            modelBuilder.Entity("Promotions.Domain.CustomerRelations.CustomerRelation", b =>
                {
                    b.Navigation("DeliveryPoints");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Promotions.Domain.ProductDetails.PromoProductDetail", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Promotions.Domain.Products.PromoProduct", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("MeasureFields");
                });

            modelBuilder.Entity("Promotions.Domain.PromoActions.PromoAction", b =>
                {
                    b.Navigation("DeliveryPoints");

                    b.Navigation("Participants");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
