// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Promotions.Infrastructure.Persistence;

#nullable disable

namespace Promotions.Infrastructure.Migrations
{
    [DbContext(typeof(PromotionsDbContext))]
    [Migration("20260223100000_FixBigIntColumns")]
    partial class FixBigIntColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Promotions.Domain.Articles.PromoArticle", b =>
                {
                    b.Property<string>("CodDiv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODDIV");

                    b.Property<string>("CodNode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODNODEO");

                    b.Property<string>("CodNode1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODNODE1");

                    b.Property<string>("CodNode2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODNODE2");

                    b.Property<bool?>("CodNodeN")
                        .HasColumnType("bit")
                        .HasColumnName("FROMNODEFIN");

                    b.HasKey("CodDiv", "CodNode");

                    b.ToTable("TA5150PROMOARTICLES", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.CustomerRelations.CustomerRelation", b =>
                {
                    b.Property<string>("CodHier")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CODHER");

                    b.Property<string>("CodDiv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODDIV");

                    b.Property<string>("CodNode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CODNODE");

                    b.Property<int>("IdLevel")
                        .HasColumnType("int")
                        .HasColumnName("IDLEVEL");

                    b.Property<DateTime>("DteStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("DTESTART");

                    b.Property<string>("CodParentNode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("COOPAREANTNODE");

                    b.Property<DateTime?>("DteEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("DTEEND");

                    b.HasKey("CodHier", "CodDiv", "CodNode", "IdLevel", "DteStart");

                    b.ToTable("TB0042RELATIONS_CUST", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.DeliveryPoints.PromoDeliveryPoint", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int")
                        .HasColumnName("IDACTION");

                    b.Property<string>("CodDeliveryPoint")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CODDELIVERYPOINT");

                    b.Property<string>("CodDiv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODDIV");

                    b.Property<string>("CodHier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CODHER");

                    b.Property<string>("CodNode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CODNODE");

                    b.Property<DateTime>("DteStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("DTESTART");

                    b.Property<bool>("FlgInclusion")
                        .HasColumnType("bit")
                        .HasColumnName("FLGINCLUSION");

                    b.Property<int>("IdLevel")
                        .HasColumnType("int")
                        .HasColumnName("IDLEVEL");

                    b.HasKey("IdAction", "CodDeliveryPoint");

                    b.HasIndex("CodHier", "CodDiv", "CodNode", "IdLevel", "DteStart");

                    b.ToTable("TA501DELIVERYPOINTS", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.Measures.PromoMeasureField", b =>
                {
                    b.Property<string>("CodDiv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODDIV");

                    b.Property<string>("CodMeasure")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODMEASURE");

                    b.Property<string>("FieldName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FIELDNAME");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FORMULA");

                    b.HasKey("CodDiv", "CodMeasure", "FieldName");

                    b.ToTable("TA5118PROMOMEASUREFIELDS", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.Participants.PromoParticipants", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int")
                        .HasColumnName("IDACTION");

                    b.Property<string>("CodParticipant")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CODPARTICIPANT");

                    b.Property<string>("CodDiv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODDIV");

                    b.Property<string>("CodHier")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CODHER");

                    b.Property<string>("CodNode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CODNODE");

                    b.Property<DateTime>("DteStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("DTESTART");

                    b.Property<bool>("FlgInclusion")
                        .HasColumnType("bit")
                        .HasColumnName("FLGINCLUSION");

                    b.Property<int>("IdLevel")
                        .HasColumnType("int")
                        .HasColumnName("IDLEVEL");

                    b.HasKey("IdAction", "CodParticipant");

                    b.HasIndex("CodHier", "CodDiv", "CodNode", "IdLevel", "DteStart");

                    b.ToTable("TA8012PARTICIPANTS", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.ProductDetails.PromoProductDetail", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int")
                        .HasColumnName("IDACTION");

                    b.Property<string>("CodProduct")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODPRODUCT");

                    b.Property<int>("LevProduct")
                        .HasColumnType("int")
                        .HasColumnName("LEVPRODUCT");

                    b.Property<string>("CodDisplay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODDISPLAY");

                    b.Property<string>("CodNode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("CODNODEO");

                    b.Property<string>("CodDiv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODDIV");

                    b.Property<bool>("FlgInclusion")
                        .HasColumnType("bit")
                        .HasColumnName("FLGINCLUSION");

                    b.HasKey("IdAction", "CodProduct", "LevProduct", "CodDisplay", "CodNode", "CodDiv");

                    b.HasIndex("CodDiv", "CodNode");

                    b.ToTable("TA5026PRODUCTDETAILS", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.Products.PromoProduct", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int")
                        .HasColumnName("IDACTION");

                    b.Property<string>("CodProduct")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODPRODUCT");

                    b.Property<int>("LevProduct")
                        .HasColumnType("int")
                        .HasColumnName("LEVPRODUCT");

                    b.Property<string>("CodDisplay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODDISPLAY");

                    b.Property<string>("CodDiv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODDIV");

                    b.Property<string>("CodMeasure")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CODMEASURE");

                    b.Property<decimal?>("NumMeasure")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("NUMMEASUREA");

                    b.Property<decimal?>("PerceDiscount1")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PERCDISCOUNT1");

                    b.Property<decimal?>("PerceDiscount2")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PERCDISCOUNT2");

                    b.Property<decimal>("QtyEstimated")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("QTYESTIMATED");

                    b.HasKey("IdAction", "CodProduct", "LevProduct", "CodDisplay");

                    b.ToTable("TA502PRODUCTS", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.PromoActions.PromoAction", b =>
                {
                    b.Property<int>("IdAction")
                        .HasColumnType("int")
                        .HasColumnName("IDACTION");

                    b.Property<string>("CodDiv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODDIV");

                    b.Property<string>("DocumentKey")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DOCUMENTKEY");

                    b.Property<DateTime>("DteEndSellIn")
                        .HasColumnType("datetime2")
                        .HasColumnName("DTEENDSELLIN");

                    b.Property<DateTime>("DteEndSellOut")
                        .HasColumnType("datetime2")
                        .HasColumnName("DTEENDSELLOUT");

                    b.Property<DateTime>("DteStartSellIn")
                        .HasColumnType("datetime2")
                        .HasColumnName("DTESTARTSELLIN");

                    b.Property<DateTime>("DteStartSellOut")
                        .HasColumnType("datetime2")
                        .HasColumnName("DTESTARTSELLOUT");

                    b.Property<DateTime?>("DteToShost")
                        .HasColumnType("datetime2")
                        .HasColumnName("DTEHOST");

                    b.Property<int?>("LevParticipants")
                        .HasColumnType("int")
                        .HasColumnName("LEVPARTICIPANTS");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESACTION");

                    b.HasKey("IdAction");

                    b.ToTable("TA500PROMOACTION", (string)null);
                });

            modelBuilder.Entity("Promotions.Domain.DeliveryPoints.PromoDeliveryPoint", b =>
                {
                    b.HasOne("Promotions.Domain.PromoActions.PromoAction", "Action")
                        .WithMany("DeliveryPoints")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Promotions.Domain.CustomerRelations.CustomerRelation", "Relation")
                        .WithMany("DeliveryPoints")
                        .HasForeignKey("CodHier", "CodDiv", "CodNode", "IdLevel", "DteStart")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("Promotions.Domain.Participants.PromoParticipants", b =>
                {
                    b.HasOne("Promotions.Domain.PromoActions.PromoAction", "Action")
                        .WithMany("Participants")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Promotions.Domain.CustomerRelations.CustomerRelation", "Relation")
                        .WithMany("Participants")
                        .HasForeignKey("CodHier", "CodDiv", "CodNode", "IdLevel", "DteStart")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Action");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("Promotions.Domain.ProductDetails.PromoProductDetail", b =>
                {
                    b.HasOne("Promotions.Domain.Articles.PromoArticle", "Article")
                        .WithMany()
                        .HasForeignKey("CodDiv", "CodNode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Promotions.Domain.Products.PromoProduct", "Product")
                        .WithMany("Details")
                        .HasForeignKey("IdAction", "CodProduct", "LevProduct", "CodDisplay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Promotions.Domain.Products.PromoProduct", b =>
                {
                    b.HasOne("Promotions.Domain.PromoActions.PromoAction", "Action")
                        .WithMany("Products")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");
                });

            modelBuilder.Entity("Promotions.Domain.CustomerRelations.CustomerRelation", b =>
                {
                    b.Navigation("DeliveryPoints");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Promotions.Domain.Products.PromoProduct", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Promotions.Domain.PromoActions.PromoAction", b =>
                {
                    b.Navigation("DeliveryPoints");

                    b.Navigation("Participants");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
